

[workspace]
members = [ "logger", "minios",
    "pool_allocator",
]

[workspace.package]
version = "0.0.1"
authors = ["Rohit Patil"]
description = "Mini OS example"

[profile.dev]
panic="abort"

[profile.release]
panic="abort"
strip = true
